### ISSUE TITLE
How do I exclude bindings?

### ISSUE THREAD

**Issue by linuxer0x42** [doums/apekey#1]
Hi @doums this is very useful software, thank you for making this!

I have a question though, and my question is whether you can exclude bindings that are commented out, I tried using the `-- #` syntax around the commented out bindings but the rest of my bindings weren't picked up, also apekey was picking up the commented out bindings, is there any way to do this? If not I can just move the commented bindings outside of the bit that apekey evaluates.

**Comment by doums** [comment]
Hi, thanks.
Currently, there is no way to exclude declaratively a mapping, ie. if you comment a mapping, it will be parsed by apekey.
This is a good issue though, I'll add this feature in a next PR.

> I tried using the -- # syntax around the commented

`-- #` is the end token, as soon as apekey reach this token, it stops parsing, not a good solution

> If not I can just move the commented bindings outside of the bit that apekey evaluates.

yes could be a temporary solution

**Comment by doums** [comment]
Hey, just to let you know with the last release `0.2.0` now you can use `-- !` to ignore a keybind 

see https://github.com/doums/apekey#----keybind-ignored
